# Generated by Django 5.1.1 on 2025-11-18 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyrequester',
            name='user',
        ),
        migrations.AddField(
            model_name='moneyrequester',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
