# Generated by Django 5.1.1 on 2025-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_idempotencylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencylog',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20),
        ),
    ]
