# Generated by Django 5.1.1 on 2025-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_idempotencylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencylog',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idempotencylog',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
